### ISSUE TITLE
`VIP_Go_Feed_Cache::create()` called statically

### ISSUE THREAD

**Issue by gmazzap** [Automattic/vip-go-mu-plugins#1120]
`VIP_Go_Feed_Cache::create()` (https://github.com/Automattic/vip-go-mu-plugins/blob/master/vip-feed-cache/class-vip-go-feed-cache.php#L13) is a dynamic method, but is ts called statically by SimplePie Registry (see https://github.com/WordPress/WordPress/blob/master/wp-includes/SimplePie/Registry.php#L215).

In PHP 7+ this causes the following deprecated notice:
> Non-static method VIP_Go_Feed_Cache::create() should not be called statically.

This can be fixed by making the method static. This change would be backward-compatible because static methods can be called dynamically without issues.

I will send a PR to address this.

**Comment by rinatkhaziev** [comment]
Hi @gmazzap, unfortunately, this didn't work and resulted in a bunch of fatals, so we had to revert it. The situation is pretty much an impasse. The warning happens in the core's SimplePie dependency and there's no easy way around it. 

In order to register a custom cache handler in a legacy way (as it's done in core, currently) the handler class must be a child of `SimplePie_Cache`. The `create` method is defined as instance method there, so if we redefine `create` method as static we get a compile error `Cannot make non static method SimplePie_Cache::create() static in class VIP_Go_Feed_Cache`. 

There's a newer way of registering a cache handler, as described in this Core ticket: https://core.trac.wordpress.org/ticket/29204#comment:7 . As far as I can tell it works, but that still leaves us with a similar deprecated message for the core's WP_Feed_Cache:

Below you can see the modified version of `vipgo_feed_options` that fixes the issue, but in `fetch_feed` function the core uses the same logic `$feed->set_cache_class( 'WP_Feed_Cache' );` that results in a similar deprecated warning:

`Non-static method WP_Feed_Cache::create() should not be called statically | wp-includes/SimplePie/Registry.php:215`

```php
function vipgo_feed_options( &$feed, $url ) {
	require_once( __DIR__ . '/vip-feed-cache/class-vip-go-feed-cache.php' );
	SimplePie_Cache::register( 'vip', 'VIP_Go_Feed_Cache_Transient' );
	$feed->set_cache_location('vip://feed-cache' . $url );
}
```

**Comment by WPprodigy** [comment]
Hmm, so what is the consensus here? Any use of the core `fetch_feed()` function will throw the error.

What is the best workaround?

**Comment by rebeccahum** [comment]
This has been fixed by https://github.com/Automattic/vip-go-mu-plugins/pull/3012.
