### ISSUE TITLE
Bulk editing limitations

### ISSUE THREAD

**Issue by WPprodigy** [Automattic/vip-go-mu-plugins#1280]
"Pages" are hierarchical in WordPress, meaning you can nest pages underneath a parent. As a result, WP sets the main query's posts_per_page limit to `-1` on hierarchical post types for sorting reasons (so all of the children can show under the parent I assume).

This happens here in WordPress core: https://github.com/WordPress/WordPress/blob/c77e771c849a85b63cef1b9457ad1a501a331afa/wp-admin/includes/post.php#L1169-L1176

And on VIP, we limit bulk editing actions when there is more than a 20 `posts_per_page` limit. This happens here: https://github.com/Automattic/vip-go-mu-plugins/blob/a053b6e8b4f64e4a8ad37b39149d1a636f76b563/performance/bulk-edit.php#L71-L73

So on any page editing screen, we are imposing the bulk editing limit. This used to not be the case, but I believe this change in core amplified the bug: https://github.com/WordPress/WordPress/commit/921fd015826a442dc58444f9f07d21def54f7e03 CC @david-binda 

I see that the page edit screen still limits to 20 per page by default though, so I feel there is something we could do on the VIP logic side to accompany this behavior better.

### Replication

- On any VIP test site, add at least 21 pages. 
- Note how bulk editing is disabled.

**Comment by david-binda** [comment]
@WPprodigy 👋Thanks for the ping.

However, I don't think that the WordPress/WordPress@921fd01 is the culprit here. That commit hotfixes an issue introduced in https://github.com/WordPress/WordPress/commit/5a30da57c68595949e917645130ac01094f3c44b which only existed in a RC version of the WordPress.

I mean, reverting the changeset you identified possibly fixes the issue you are describing, but break something else. I believe that in case you were testing the version of the code prior https://github.com/WordPress/WordPress/commit/5a30da57c68595949e917645130ac01094f3c44b it would still be reproducible.

If this really were working at some point in the past, I would look for some breaking change prior https://github.com/WordPress/WordPress/commit/5a30da57c68595949e917645130ac01094f3c44b, not the https://github.com/WordPress/WordPress/commit/921fd015826a442dc58444f9f07d21def54f7e03 .

Please, let me know if it makes sense, or whether you have any related questions!
