### ISSUE TITLE
Need to update VaultPress

### ISSUE THREAD

**Issue by WPprodigy** [Automattic/vip-go-mu-plugins#1485]
Current version is 2.1.1: https://github.com/Automattic/vaultpress/releases, while we are on version 1.9.10 in this repo right now.

Unsure if any customizations are being done (since it's not a submodule), but this error in particular is pretty noisy: https://github.com/Automattic/vaultpress/issues/74

**Comment by jonathanstegall** [comment]
I've also noticed that when I run WordPress 5.4 RC2 (including after updating to most recent version of repo), it fills up my logs with this entry:

```
PHP Deprecated:  private_to_published is <strong>deprecated</strong> since version 2.3.0! Use private_to_publish instead. in ~/Sites/minnpost-wordpress/wp-includes/functions.php on line 5088
```

**Comment by paulschreiber** [comment]
This is also generating warnings with PHP 7.4:
```
Deprecated: Array and string offset access syntax with curly braces is deprecated in /srv/www/theundefeated/public_html/wp-content/mu-plugins/vaultpress/vaultpress.php on line 728

Deprecated: Array and string offset access syntax with curly braces is deprecated in /srv/www/theundefeated/public_html/wp-content/mu-plugins/vaultpress/vaultpress.php on line 1316

Deprecated: Array and string offset access syntax with curly braces is deprecated in /srv/www/theundefeated/public_html/wp-content/mu-plugins/vaultpress/vaultpress.php on line 1317

Deprecated: Array and string offset access syntax with curly braces is deprecated in /srv/www/theundefeated/public_html/wp-content/mu-plugins/vaultpress/vaultpress.php on line 1318

Deprecated: Array and string offset access syntax with curly braces is deprecated in /srv/www/theundefeated/public_html/wp-content/mu-plugins/vaultpress/vaultpress.php on line 1320
```

**Comment by trepmal** [comment]
VIP Hack (simple fix, but note the outdated comment...):
https://github.com/Automattic/vip-go-mu-plugins/blob/73f73f74fa2c7b6b30e1d74515e14c6c3c5dbb16/vaultpress/class.vaultpress-cli.php#L21-L23

Deprecated hook (another simple fix, would be nice to give the community an opportunity if time allows):
Issue opened https://github.com/Automattic/vaultpress/issues/88

php 7.4 compat `Array and string offset access syntax` issues:
Fixed in upstream updates https://github.com/Automattic/vaultpress/pull/77

Still sifting through the other changes between 1.9.10 and  2.1.1, but it looks pretty straightforward at a glance

**Comment by uxcitizen** [comment]
The new version of VaultPress has been deployed in https://github.com/Automattic/vip-go-mu-plugins/pull/1522

**Comment by davisshaver** [comment]
Could we please get an expedited review/new version for this PR? https://github.com/Automattic/vaultpress/pull/91
