### ISSUE TITLE
Consistent use of `git` or `https` protocol for submodules

### ISSUE THREAD

**Issue by ethitter** [Automattic/vip-go-mu-plugins#298]
Right now, our submodules use a random mix of `git` and `https` protocols. This isn't breaking anything that I'm aware of, but it'd still be nice to be consistent.

https://github.com/Automattic/vip-go-mu-plugins/blob/f9e87113dea10fc77f5eaa1d5bacc3490c24280e/.gitmodules

**Comment by mdrovdahl** [comment]
It appears this does break things. It causes access errors when running `git clone https://github.com/Automattic/vip-go-mu-plugins.git --recursive` without a Github ssh keypair. 

h/t @alexeilinykh who stumbled across this today.

**Comment by simonwheatley** [comment]
All client repos (to date) are private, so need some form of authentication. For an automatic site provisioning system, this means that some form of authentication is required to bring the client repo in during the provision. I suggest we enhance our documentation to suggest all client devs use SSH authentication, then we can key forward while provisioning to make that as seamless as possible and change all submodule references to SSH rather than HTTPS.

**Comment by ethitter** [comment]
@simonwheatley Good point. I'm in favor of closing this without merging, letting messaging solve this for us.

@mdrovdahl Please reopen if you disagree.

**Comment by mdrovdahl** [comment]
WFM. I updated https://vip.wordpress.com/documentation/vip-go/local-vip-go-development-environment/ to state that ssh protocols are the _one true way_.
