### ISSUE TITLE
Alloptions: Disrepency in size counts

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#432]
Email says "options is up to 786 KB [...] size when serialized: 805253"

wp-cli shows: 

```
Total size of all option values for this blog: 432 KB
Size of serialized alloptions for this blog: 786 KB
```

We should make sure the values are consistent across the board.

**Comment by nickdaugherty** [comment]
The difference in the email subject compared to the string inside the email body is that the former is run through `size_format()`, and the latter isn't. I've tweaked this behavior in https://github.com/Automattic/vip-go-mu-plugins/pull/438 to use the human-friendly size in both spots.

I also changed the CLI to use `strlen()` (which is what the alerting code uses, and what we want here) instead of `mb_strlen()`.
