### ISSUE TITLE
Add blog id to vip/v1/sites REST endpoint

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#456]
It would be useful to have the blog id for each multisite site, for a variety of things like importing media.

https://github.com/Automattic/vip-go-mu-plugins/blob/51945764f3835142817d93bc8e1c1c0c14c2f6d6/vip-rest-api.php#L125-L127

**Comment by ethitter** [comment]
Before we add too much more to the endpoint, I want to introduce some sort of authentication so that we can include private sites in the list. We've a number of problems now as a result of them not turning up. Something akin to what we do for Cron, perhaps with an IP whitelist, should suffice. I've been meaning to do this for a while now, but it's become more urgent thanks to things like #431 and http://wp.me/p6jPRI-O8.

**Comment by nickdaugherty** [comment]
@ethitter do you think it's worth holding off on adding the blog id right now?

it's blocking some work I'm doing on a media scraping importer (https://github.com/Automattic/vip-cli/pull/121) because I'd like to be able to automatically find the site's blog id for constructing `wp-content/uploads/sites/:ID/` urls when scraping media from external servers.

Alternatively we can have the human running the importer find the blog id and pass it as an argument to the command if we don't want to add the id here.

**Comment by mjangda** [comment]
> we can have the human running the importer find the blog id and pass it as an argument to the command if we don't want to add the id here.

This seems like a better idea for now. We need to add auth before we expand this endpoint any further; related #454

**Comment by nickdaugherty** [comment]
Alright - will go ahead with manual blog ids for now.
