### ISSUE TITLE
Not receiving auth codes with SMS as backup 2FA method 

### ISSUE THREAD

**Issue by prhomhyse** [Automattic/vip-go-mu-plugins#4590]
## Expected/Desired Behavior

When you click the option to use SMS (when it's the backup 2FA method), you should be able to receive the codes via SMS, except in cases where your carrier is down.

<img width="451" align="center" alt="Screenshot 2023-06-09 at 18 12 12" src="https://github.com/Automattic/vip-go-mu-plugins/assets/12263278/d8c78ac6-73f0-4010-bc9e-7af5d38c8431">

## Actual Behavior

You don't receive any codes when you click the option to use SMS, like in the above screenshot. 

I guess that the Email or another primary method was already fired when you tried logging in.

## Steps to Reproduce the Problem

1. Set up Email or other methods as the Primary 2FA method.
1. Set up SMS as the Secondary 2FA method.
1. In incognito mode, try logging in and click "use your backup method: SMS" 
1. Did you receive any SMS of the 2FA codes? 

## Additional notes

We tested TOTP and Email as both primary and secondary methods and received codes via email, and the TOTP-generated codes worked every time. 
SMS works only when it's the primary method, but that's also considering when the carrier isn't experiencing issues.

**Comment by ThirdEyeRose** [comment]
I am also experiencing this issue as of August 2nd, 2023.

**Comment by GaryJones** [comment]
After entering a username and password, the primary verification (at least for email) is shown at a URL path of `/wp-login.php`.

The link to use a backup method is generated in the Two Factor plugin - it [includes](https://github.com/Automattic/vip-go-mu-plugins/blob/f325e3ccf7842d99332f8eaf8e51df316493bb5c/shared-plugins/two-factor/class-two-factor-core.php#L757) an action of `validate_2fa`. e.g. `/wp-login.php?action=validate_2fa&provider=Two_Factor_SMS&wp-auth-id=...&wp-auth-nonce=...&redirect_to=...&rememberme=...`

For some reason, the [code in the vip-go-mu-plugins](https://github.com/Automattic/vip-go-mu-plugins/blob/f325e3ccf7842d99332f8eaf8e51df316493bb5c/wpcom-vip-two-factor/sms-provider.php#L124-L126) only sends a code if the `action` parameter is not `validate_2fa` - hence, no code is sent for SMS set as secondary.

This originated from [this change](https://github.com/Automattic/vip-go-mu-plugins/commit/5e5584ce2ce4a0f63e4973571965094be5a1a6cb) which was made to stop repeated codes being generated on failed logins.

Knowing this, I gave an incorrect code, and was redirected to `/wp-login.php?action=validate_2fa`. As such, I think the conditional could be updated to check for the existence of a `provider` querystring parameter or similar so that it blocks repeated codes being generated but does generate them on the first switch to using SMS as backup.
