### ISSUE TITLE
Jetpack Start: Multisite Support

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#594]
It would nice to have a way to run the `connect` command against all sites in a network.

**Comment by ethitter** [comment]
I started looking at this today; should have something to review either tonight or tomorrow.

Archived, spammed, and deleted sites will be omitted. Otherwise, this should be pretty straightforward for the user.

Should the `cancel` command also get MS support? (If so, that one would cover every site in the blogs table, regardless of status)

**Comment by mjangda** [comment]
This is done.
