### ISSUE TITLE
a8c-files: Store filesize on upload

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#695]
Because images are stored in a cloud service, we have no access to them locally to get the filesize. Core will try to access the filesize from attachment metadata if set so we can just store it on upload.

- [x] Hooks on file upload and/or generate metadata to add the `filesize`.
- [ ] wp-cli script to backfill attachment `filesize` values.

Do we only need to worry about images? Or all file types?

/cc @emrikol

**Comment by emrikol** [comment]
I think the [`validate-attachments` CLI that I wrote](https://github.com/Automattic/vip-go-mu-plugins/blob/56d2124859b2c51ef02386fbc31868321f17cfb1/wp-cli/vip-migrations.php#L91) is just a few option updates away from being a backfill script, might be a good base to start with.

I'd say we want to worry about all media in the media library.  IIRC, one of the reasons this came up was because a client was wanting to list the size of PDF files on a download page.

**Comment by TheCrowned** [comment]
@mjangda A client reported that calling
`wp_remote_head( wp_get_attachment_url( $attachment_id ) )['headers']['content-length']`
works fine on VIP Go to fetch file filesize given an attachment ID. Is this a viable option to implement a `vip_go_filesize()` function?

If that is, we could then hook to [`wp_generate_attachment_metadata`](https://core.trac.wordpress.org/browser/tags/4.9/src/wp-admin/includes/image.php#L293) to add the `['size']` metadata in the db on new uploads. 

This would be enough for new uploads, and then if needed we could also have a CLI script to backfill using the above function.
