### ISSUE TITLE
Remove wpcom_vip_include_active_plugins()

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#848]
Now that (almost) all plugins are removed, I think we can remove `wpcom_vip_include_active_plugins()` and its `plugins_loaded` hook. 

An edge case scenario arises, when a site had `vip-go-elasticsearch` enabled via UI at some point in the past (and there is a subsequent entry in the `wpcom_vip_active_plugins` option), but has since migrated to loading via code, then onto Jetpack Search - `vip-go-elasticsearch` is still loaded with no way to disable other than removing the option, which is unexpected.

What do you think @scottsweb?

**Comment by nickdaugherty** [comment]
The other aspect of this is that we don't show these plugins as enabled in the Plugins UI anymore (right?), so there is no indication of it being enabled and no way to disable.

**Comment by scottsweb** [comment]
Correct, these are not shown as active anymore because that option (`wpcom_vip_active_plugins`) is effectively out of action these days.

There are only three plugins I believe that could be impacted by this bug:

https://github.com/Automattic/vip-go-mu-plugins/blob/a05aa70ce1cddc60e5106829e63166ad3c036d48/vip-helpers/vip-utils.php#L1075-L1079

and only sites without the `WPCOM_VIP_DISABLE_SHARED_PLUGINS` constant will suffer from the issue. All sites that went through the transition process should have this in place. If my memory serves me correctly the site that has prompted this issue decided to implement a patch without our help and did not include the `WPCOM_VIP_DISABLE_SHARED_PLUGINS` constant or it is possible it was later removed. 

I am just going to check the plugin stats but I am in favour of retiring `wpcom_vip_include_active_plugins` and will put together a PR if the stats look sensible.

**Comment by scottsweb** [comment]
See our P2 for a follow up

**Comment by WPprodigy** [comment]
Closing per https://github.com/Automattic/vip-go-mu-plugins/pull/849#issuecomment-990257085
